#!/usr/bin/env php
<?php
require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/common/config/dotenv.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');

$appName = getenv('APPLICATION');
$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/' . $appName . '/config/main.php')
);

$application = new yii\console\Application($config);
$application->setVendorPath('/app/vendor');
$exitCode = $application->run();
exit($exitCode);
